server.port=8761
spring.application.name=eureka-server

# Eureka no debe registrarse a sí mismo — él ES el registro
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Nombre que aparece en el dashboard
eureka.instance.hostname=localhost
eureka.server.enable-self-preservation=false